### ISSUE TITLE
npm install missing dependency (Ionic)

### ISSUE THREAD

**Issue by elsener** [matchmore/js-sdk#7]
Using IONIC 3 (but I suspect same behavior in other projects) some dependency to `api` is missing when installing using npm and README is wrong.

# How to reproduce
1) Start a blank project with Ionic CLI:
`ionic start myProject`

2) Go in **myProject** directory and follow the matchmore npm installation instructions as described in README:
`npm install @matchmore/matchmore --save`

3) Edit `src/app/app.component.ts` to add matchmore as described in README:
```import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { Manager } from "matchmore";

import { HomePage } from '../pages/home/home';
@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = HomePage;
  manager: any;

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      splashScreen.hide();
        this.manager = new Manager(
          "<Your api key>"
        )
    });
  }
}
```

4) Start ionic with: `ionic serve`

5) Compilation error, README is wrong, need to update `src/app/app.component.ts`:
`import { Manager } from "matchmore";`
to
`import { Manager } from "@matchmore/matchmore";` 
(That will match the npm install)

6) Start ionic with: `ionic serve`
-> compilation succeed, go to `http://localhost:8100/` to view your app

7) Runtime error `./api` dependency is missing (this is due to matchmore npm):
![api_error](https://user-images.githubusercontent.com/24521573/41222694-fd0998ec-6d67-11e8-8f7d-504b17e248d7.png)

# TODO

- [x] Update README (point 5): `import { Manager } from "@matchmore/matchmore";` 
- [x] Fix: Runtime error `./Api` dependency is missing

**Comment by lmlynik** [comment]
corrected and should work with 0.7.3
